version: 0.2

env:
  parameter-store:
    DOCKERHUB_USERNAME: "/myapp/dockerhub-username"
    DOCKERHUB_PASSWORD: "/myapp/dockerhub-password"
    DOCKERHUB_IMAGE_NAME: "/myapp/dockerhub-image-name"

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
  build:
    commands:
      - echo Running tests...
      - npm test
      - echo Building Docker image...
      - docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_IMAGE_NAME .
  post_build:
    commands:
      - echo Pushing Docker image to Docker Hub...
      - docker push $DOCKERHUB_USERNAME/$DOCKERHUB_IMAGE_NAME

artifacts:
  files:
    - '**/*'